name-template: '$NEXT_PATCH_VERSION🌈'
tag-template: '$NEXT_PATCH_VERSION'
filter-by-commitish: true
commitish: release/5.9
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 
      - 'chore'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
prerelease: true
version-resolver:
  major:
    labels:
      - 'breakingchange'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: minor 
template: |
  ## Changes
  $CHANGES
