name-template: 'v$RESOLVED_VERSION 💎'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🧨 Hot fixes'
    labels:
      - 'hot fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
prerelease: true
version-resolver:
  patch:
    labels:
      - 'hot fix'
      - 'bug'
  default: patch 
template: |
  ## Changes

  $CHANGES