on:
  push:
    branches:
      - main
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    environment: CircleCI
    steps:
      - name: release
        id: abcdef
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}
