name: Release Flow
on: [push, workflow_dispatch]

jobs:
  new-release:
    #if: $GITHUB_REF_NAME == 'main'
    name: New release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_REF_NAME
      - name: 'Get last draft version'
        # TODO: How to handle if a patch has replaced the last minor?
        id: last_draft_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release"
          view_top: 1
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
      - name: 'Create a new branch'
        run: |
          FULL_VERSION=$(echo ${{ steps.last_release.outputs.draft }})
          echo $FULL_VERSION
          echo ${FULL_VERSION:1}

