name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types: [closed]
jobs:
  update_release_draft:
    if: ${{ github.event.pull_request.merged  ||  github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Check github variables'
        run: |
          echo "Github is merged: ${{ github.event.pull_request.merged }}"
          echo "Event name: ${{ github.event_name }} "
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-main.yml # located in .github/ in default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
