name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches: 
      - 'release/**'
    types: [closed]
jobs:
  update_release_draft:
    if: ${{ github.event.pull_request.merged  ||  github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-release-branch.yml # located in .github/ in default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
