name: 'Publish Prerelease'

on:
  repository_dispatch:
    types: [release_builds_ready]

jobs:
  update_release:
    runs-on: ubuntu-latest
    environment: CircleCI
    steps:
      - uses: actions/checkout@v2
      - name: Set up download path
        run: |
           echo "DOWNLOAD_DIR=downloaded-artifacts" >> $GITHUB_ENV
           echo "LAST_DRAFT_TAG=v${{ fromJSON(github.event.client_payload.metadata).version }} >> $GITHUB_ENV"
      - name: Download Artifacts from CircleCI
        run: |
          ./download-artifacts.py --circleci-token ${{ secrets.CIRCLE_CI_TOKEN }} \
             --user ${{ github.event.client_payload.username }} \
             --repo-name ${{ github.event.client_payload.reponame }} \
             --build-number ${{ github.event.client_payload.build_num }} \
             --download-dir ${{ env.DOWNLOAD_DIR }}
      - name: "Get latest patch from branch version ${{ env.LAST_DRAFT_TAG }}"
        uses: cardinalby/git-get-release-action@v1
        id: latest_draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseNameRegEx: "${{ env.LAST_DRAFT_TAG }}"
          latest: true
          draft: true
      - name: Upload binaries to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./${{ env.DOWNLOAD_DIR }}/*
          prerelease: true
          release_id: ${{ steps.latest_draft.outputs.id }}
      - name: Publish the release ${{ env.LAST_DRAFT_TAG }}
        run: |
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" /repos/$REPOSITORY/releases/$RELEASE_ID  -f target_commitish='main' -F draft=false -F prerelease=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          RELEASE_ID: ${{ steps.latest_draft.outputs.id }}


